name: build

on:
  push:
    tags: [ 'v*.*.*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build-mp:
    env:
      UPLOAD_KEY: ${{ secrets.UPLOAD_KEY }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Mini Program
        run: yarn install && yarn build:mp-weixin
      - name: Upload artifact
        run: node scripts/upload.mjs
      - name: Send Change Log
        run: node scripts/send-changelog.mjs
